# Generated by Django 5.0.6 on 2024-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('app_name', models.CharField(choices=[('حسابداری', 'حسابداری'), ('مدیریت پروژه', 'مدیریت پروژه')], max_length=50, verbose_name='app_name')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processs',
            },
        ),
    ]
