# Generated by Django 5.0.6 on 2024-08-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('processmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='group'),
            preserve_default=False,
        ),
    ]
