# Generated by Django 5.0.6 on 2024-08-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processmanagement', '0003_remove_process_group_process_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='app_name',
            new_name='process_app_name',
        ),
    ]
