# Generated by Django 5.0.6 on 2024-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processmanagement', '0004_rename_app_name_process_process_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='priority'),
        ),
    ]
