# Generated by Django 5.0.6 on 2024-06-26 01:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='page',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='short_description'),
        ),
    ]
