# Generated by Django 5.0.6 on 2024-10-02 06:16

import django.db.models.deletion
import utility.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('آقای', 'آقای'), ('خانم', 'خانم'), ('شرکت', 'شرکت'), ('دکتر', 'دکتر'), ('مهندس', 'مهندس')], max_length=50, verbose_name='prefix')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره همراه')),
                ('bio', models.CharField(blank=True, max_length=50, null=True, verbose_name='بیو')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/', verbose_name='تصویر')),
                ('header_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/header/', verbose_name='سربرگ')),
                ('enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('can_login', models.BooleanField(default=False, verbose_name='لاگین می کند ?')),
                ('status', models.CharField(choices=[('AAA', 'AAA'), ('BBB', 'BBB')], default='AAA', max_length=50, verbose_name='وضعیت')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=50, verbose_name='جنسیت')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
