# Generated by Django 5.0.6 on 2024-08-07 03:13

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0002_page_description_page_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'AccountGroup',
                'verbose_name_plural': 'AccountGroups',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
            ],
            options={
                'verbose_name': 'AccountingDocument',
                'verbose_name_plural': 'AccountingDocuments',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('color_origin', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], max_length=50, null=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'EventCategory',
                'verbose_name_plural': 'EventCategories',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='ProductOrService',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='بارکد')),
            ],
            options={
                'verbose_name': 'ProductOrService',
                'verbose_name_plural': 'ProductOrServices',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='tel')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('logo_origin', models.ImageField(upload_to='accounting/images/account', verbose_name='logo')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='BasicAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('accountgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountgroup', verbose_name='account group')),
            ],
            options={
                'verbose_name': 'BasicAccount',
                'verbose_name_plural': 'BasicAccounts',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('در جریان', 'در جریان'), ('آماده تحویل', 'آماده تحویل'), ('تایید شده', 'تایید شده'), ('تحویل شده', 'تحویل شده'), ('کنسل شده', 'کنسل شده'), ('برگشت از تحویل', 'برگشت از تحویل'), ('تایید نهایی شده', 'تایید نهایی شده'), ('پاس شده', 'پاس شده'), ('مانده حساب از قبل', 'مانده حساب از قبل')], default='پیش نویس', max_length=50, verbose_name='وضعیت')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('همراه بانک', 'همراه بانک'), ('فروش کالا', 'فروش کالا'), ('فروش خدمات', 'فروش خدمات'), ('نقدی', 'نقدی'), ('چک', 'چک'), ('کارتخوان', 'کارتخوان'), ('فیش بانکی', 'فیش بانکی'), ('کارت به کارت', 'کارت به کارت')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت')),
                ('event_datetime', models.DateTimeField(verbose_name='تاریخ تراکنش')),
                ('accounting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.accountingdocument', verbose_name='سند حسابداری')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='ثبت شده توسط')),
                ('pay_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_from', to='accounting.account', verbose_name='پرداخت کننده')),
                ('pay_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_to', to='accounting.account', verbose_name='دریافت کننده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.eventcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='AccountingDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedehkar', models.IntegerField(default=0, verbose_name='بدهکار')),
                ('bestankar', models.IntegerField(default=0, verbose_name='بستانکار')),
                ('balance', models.IntegerField(default=0, verbose_name='بالانس')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('accounting_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingdocument', verbose_name='accountingdocument')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'AccountingDocumentLine',
                'verbose_name_plural': 'AccountingDocumentLines',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='EventPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ چاپ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.event', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'EventPrint',
                'verbose_name_plural': 'EventPrints',
            },
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'FinancialDocument',
                'verbose_name_plural': 'FinancialDocuments',
            },
            bases=(utility.models.LinkHelper, models.Model),
        ),
        migrations.CreateModel(
            name='MoeinAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('basicaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.basicaccount', verbose_name='basicaccount')),
            ],
            options={
                'verbose_name': 'MoeinAccount',
                'verbose_name_plural': 'MoeinAccounts',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='account',
            name='moeinaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.moeinaccount', verbose_name='moein account'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productorservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.productorservice')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            bases=('accounting.productorservice',),
        ),
    ]
