# Generated by Django 5.0.6 on 2024-08-07 01:03

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'AccountingDocumentLine',
                'verbose_name_plural': 'AccountingDocumentLines',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('lines', models.ManyToManyField(blank=True, to='accounting.accountingdocumentline', verbose_name='accounting document lines ')),
            ],
            options={
                'verbose_name': 'AccountingDocument',
                'verbose_name_plural': 'AccountingDocuments',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
