# Generated by Django 5.0.6 on 2024-08-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bedehkar',
            field=models.IntegerField(default=0, verbose_name='bedehkar'),
        ),
        migrations.AddField(
            model_name='account',
            name='bestankar',
            field=models.IntegerField(default=0, verbose_name='bestankar'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='bedehkar',
            field=models.IntegerField(default=0, verbose_name='bedehkar'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='bestankar',
            field=models.IntegerField(default=0, verbose_name='bestankar'),
        ),
        migrations.AddField(
            model_name='basicaccount',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='basicaccount',
            name='bedehkar',
            field=models.IntegerField(default=0, verbose_name='bedehkar'),
        ),
        migrations.AddField(
            model_name='basicaccount',
            name='bestankar',
            field=models.IntegerField(default=0, verbose_name='bestankar'),
        ),
        migrations.AddField(
            model_name='moeinaccount',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='moeinaccount',
            name='bedehkar',
            field=models.IntegerField(default=0, verbose_name='bedehkar'),
        ),
        migrations.AddField(
            model_name='moeinaccount',
            name='bestankar',
            field=models.IntegerField(default=0, verbose_name='bestankar'),
        ),
        migrations.AlterField(
            model_name='account',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='accounting/images/account', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='accountingdocumentline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='accountingdocumentline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.event', verbose_name='event'),
        ),
    ]
