# Generated by Django 5.0.6 on 2024-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='111', max_length=200, verbose_name='type'),
            preserve_default=False,
        ),
    ]
