# Generated by Django 5.0.6 on 2024-08-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(default='1', max_length=200, verbose_name='code'),
            preserve_default=False,
        ),
    ]
