# Generated by Django 5.0.6 on 2024-06-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='account',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tel'),
        ),
    ]
