# Generated by Django 5.0.6 on 2024-08-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeinaccount',
            name='basic_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.basicaccount', verbose_name='basicaccount'),
        ),
    ]
