# Generated by Django 5.0.6 on 2024-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moeinaccount',
            old_name='parent',
            new_name='moein_account',
        ),
        migrations.RenameField(
            model_name='tafsiliaccount',
            old_name='parent',
            new_name='tafsili_account',
        ),
    ]
