# Generated by Django 5.0.6 on 2024-08-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingdocumentline_accountingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocumentline',
            name='bedehkar',
            field=models.IntegerField(default=0, verbose_name='بدهکار'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='bestankar',
            field=models.IntegerField(default=0, verbose_name='بستانکار'),
        ),
    ]
