# Generated by Django 5.0.6 on 2024-09-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_accountingdocumentline_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
