# Generated by Django 5.0.6 on 2024-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_bedehkar_account_bestankar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
    ]
