# Generated by Django 5.0.6 on 2024-09-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_account_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tafsiliaccount',
            name='moein_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.moeinaccount', verbose_name='moein account'),
        ),
    ]
