# Generated by Django 5.0.6 on 2024-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_parent_moeinaccount_moein_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocumentline',
            name='title',
            field=models.CharField(default='ssss', max_length=500, verbose_name='title'),
            preserve_default=False,
        ),
    ]
