# Generated by Django 5.0.6 on 2024-08-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingdocumentline_bedehkar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocumentline',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='بالانس'),
        ),
    ]
