# Generated by Django 5.0.6 on 2024-09-01 00:31

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_accountingdocumentline_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdocument',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 1, 0, 30, 58, 433090, tzinfo=datetime.timezone.utc), verbose_name='date_added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 31, 2, 645005, tzinfo=datetime.timezone.utc), verbose_name='date_modified '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date_time'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 31, 28, 71132, tzinfo=datetime.timezone.utc), verbose_name='date_modified '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date_time'),
        ),
    ]
