# Generated by Django 5.0.6 on 2024-09-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accountingdocument_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingdocumentline',
            name='date_modified',
            field=models.DateTimeField(null=True, verbose_name='date_modified '),
        ),
    ]
