# Generated by Django 5.0.6 on 2024-09-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_accountingdocumentline_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pure_code',
            field=models.IntegerField(default=0, verbose_name='pure_code'),
        ),
        migrations.AlterField(
            model_name='accountingdocument',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date_modified '),
        ),
    ]
